print('Exercicio 5')
funcionarios= (input('Nome do funcionario:') )
horas= float(input('Horas trabalhadas:'))
valor_hora= float(input('Valor recebido por hora:'))
salario= (horas *valor_hora) 
print (f'{funcionarios} recebeu seu salario de R$:{salario}.')